# proxe's defaults
defaults = {
  'name panel': {
    'location': 'UI',
    'pin active object': False,
    'pin active bone': False,
    'hide find & replace': False,
    'filters': False,
    'shortcuts': False,
    'display names': False,
    'search': '',
    'clear search': True,
    'regex': False,
    'mode': 'LAYERS',
    'groups': True,
    'action': True,
    'grease pencil': True,
    'constraints': True,
    'modifiers': True,
    'bone groups': True,
    'bone constraints': True,
    'vertex groups': True,
    'shapekeys': True,
    'uvs': True,
    'vertex colors': True,
    'materials': True,
    'textures': True,
    'particle systems': True,
    'bone mode': 'LAYERS',
    'display bones': False,
  },

  'properties panel': {
    'location': 'UI'
  },

  'shared': {
    'large popups': False,
    'sort': True,
    'type': 'ALPHABETICAL',
    'axis': 'X',
    'invert': False,
    'count': True,
    'link': False,
    'pad': 0,
    'start': 1,
    'step': 1,
    'separator': '-',
    'ignore': False
  },

  'auto name': {
    'mode': 'SCENE',
    'objects': False,
    'constraints': True,
    'modifiers': True,
    'object data': False,
    'bone constraints': True,
    'object type': 'ALL',
    'constraint type': 'ALL',
    'modifier type': 'ALL',

    'object names': {
      'prefix': True,
      'mesh': 'geo-',
      'curve': 'crv-',
      'surface': 'sfc-',
      'meta': 'mta-',
      'font': 'txt-',
      'armature': 'rig-',
      'lattice': 'lat-',
      'empty': 'ept-',
      'speaker': 'spk-',
      'camera': 'cam-',
      'lamp': 'lmp-',
    },

    'constraint names': {
      'prefix': False,
      'camera solver': 'camera-solver',
      'follow track': 'follow-track',
      'object solver': 'object-solver',
      'copy location': 'copy-location',
      'copy rotation': 'copy-rotation',
      'copy scale': 'copy-scale',
      'copy transforms': 'copy-transforms',
      'limit distance': 'limit-distance',
      'limit location': 'limit-location',
      'limit rotation': 'limit-rotation',
      'limit scale': 'limit-scale',
      'maintain volume': 'maintain-volume',
      'transform': 'transform',
      'clamp to': 'clamp-to',
      'damped track': 'damped-track',
      'inverse kinematics': 'inverse-kinematics',
      'locked track': 'locked-track',
      'spline inverse kinematics': 'spline-inverse-kinematics',
      'stretch to': 'stretch-to',
      'track to': 'track-to',
      'action': 'action',
      'child of': 'child-of',
      'floor': 'floor',
      'follow path': 'follow-path',
      'pivot': 'pivot',
      'rigid body joint': 'rigid-body-joint',
      'shrinkwrap': 'shrinkwrap',
    },

    'modifier names': {
      'prefix': False,
      'data transfer': 'data-transfer',
      'mesh cache': 'mesh-cache',
      'normal edit': 'normal-edit',
      'uv project': 'uv-project',
      'uv warp': 'uv-warp',
      'vertex weight edit': 'vertex-weight-edit',
      'vertex weight mix': 'vertex-weight-mix',
      'vertex weight proximity': 'vertex-weight-proximity',
      'array': 'array',
      'bevel': 'bevel',
      'boolean': 'boolean',
      'build': 'build',
      'decimate': 'decimate',
      'edge split': 'edge-split',
      'mask': 'mask',
      'mirror': 'mirror',
      'multiresolution': 'multiresolution',
      'remesh': 'remesh',
      'screw': 'screw',
      'skin': 'skin',
      'solidify': 'solidify',
      'subdivision surface': 'subdivision-surface',
      'triangulate': 'triangulate',
      'wireframe': 'wireframe',
      'armature': 'armature',
      'cast': 'cast',
      'corrective smooth': 'corrective-smooth',
      'curve': 'curve',
      'displace': 'displace',
      'hook': 'hook',
      'laplacian smooth': 'laplacian-smooth',
      'laplacian deform': 'laplacian-deform',
      'lattice': 'lattice',
      'mesh deform': 'mesh-deform',
      'shrinkwrap': 'shrinkwrap',
      'simple deform': 'simple-deform',
      'smooth': 'smooth',
      'warp': 'warp',
      'wave': 'wave',
      'cloth': 'cloth',
      'collision': 'collision',
      'dynamic paint': 'dynamic-paint',
      'explode': 'explode',
      'fluid simulation': 'fluid-simulation',
      'ocean': 'ocean',
      'particle instance': 'particle-instance',
      'particle system': 'particle-system',
      'smoke': 'smoke',
      'soft body': 'soft-body',
    },

    'object data names': {
      'prefix': False,
      'mesh': 'mesh',
      'curve': 'curve',
      'surface': 'surface',
      'meta': 'meta',
      'font': 'text',
      'armature': 'armature',
      'lattice': 'lattice',
      'empty': 'empty',
      'speaker': 'speaker',
      'camera': 'camera',
      'lamp': 'lamp',
    },
  },

  'batch name': {
    'mode': 'SCENE',
    'actions': False,
    'action groups': False,
    'grease pencil': False,
    'pencil layers': False,
    'objects': False,
    'groups': False,
    'constraints': False,
    'modifiers': False,
    'object data': False,
    'bone groups': False,
    'bones': False,
    'bone constraints': False,
    'vertex groups': False,
    'shapekeys': False,
    'uvs': False,
    'vertex colors': False,
    'materials': False,
    'textures': False,
    'particle systems': False,
    'particle settings': False,
    'object type': 'ALL',
    'constraint type': 'ALL',
    'modifier type': 'ALL',
    'sensors': False,
    'controllers': False,
    'actuators': False,
    'line sets': False,
    'linestyles': False,
    'linestyle modifiers': False,
    'linestyle modifier type': 'ALL',
    'scenes': False,
    'render layers': False,
    'worlds': False,
    'libraries': False,
    'images': False,
    'masks': False,
    'sequences': False,
    'movie clips': False,
    'sounds': False,
    'screens': False,
    'keying sets': False,
    'palettes': False,
    'brushes': False,
    'nodes': False,
    'node labels': False,
    'frame nodes': False,
    'node groups': False,
    'texts': False,
    'ignore action': False,
    'ignore grease pencil': False,
    'ignore object': True,
    'ignore group': False,
    'ignore constraint': False,
    'ignore modifier': False,
    'ignore bone': False,
    'ignore bone group': False,
    'ignore bone constraint': False,
    'ignore object data': True,
    'ignore vertex group': False,
    'ignore shapekey': False,
    'ignore uv': False,
    'ignore vertex color': False,
    'ignore material': False,
    'ignore texture': False,
    'ignore particle system': False,
    'ignore particle setting': False,
    'custom': '',
    'insert': False,
    'insert at': 0,
    'find': '',
    'regex': False,
    'replace': '',
    'prefix': '',
    'suffix': '',
    'suffix last': False,
    'trim start': 0,
    'trim end': 0,
    'cut start': 0,
    'cut amount': 0,
  },

  'copy name': {
    'mode': 'SCENE',
    'source': 'OBJECT',
    'objects': False,
    'object data': True,
    'materials': False,
    'textures': False,
    'particle systems': False,
    'particle settings': False,
    'use active object': False,
  },
}
